/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package projectrest.Presentacion;

import javax.swing.JInternalFrame;

/**
 *
 * @author Rafael
 */
public class Frm_Principal extends javax.swing.JFrame {

    private JInternalFrame main_frame;

    /**
     * Creates new form Frm_Principal
     */
    public Frm_Principal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        this.main_frame = null;

        // Cargar el login
        this.loadLogin();
    }

    public void loadLogin() {
        Frm_Login frm = new Frm_Login();
        this.visibleFrame(frm);
    }

    public void centerInternalFrame(JInternalFrame internalFrame) {
        int x = (Principal.getWidth() - internalFrame.getWidth()) / 2;
        int y = (Principal.getHeight() - internalFrame.getHeight()) / 2;
        internalFrame.setLocation(x, y);
    }

    // Vista SINGLETON
    public void visibleFrame(JInternalFrame frm) {
        if (this.main_frame != null) {
            this.main_frame.setVisible(false);
            Principal.remove(this.main_frame);
        }
        this.main_frame = frm;
        Principal.add(frm);
        frm.setVisible(true);
        this.centerInternalFrame(frm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Principal = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenMesas = new javax.swing.JMenuItem();
        MenPlatos = new javax.swing.JMenuItem();
        MenClientes = new javax.swing.JMenuItem();
        MenEmpleados = new javax.swing.JMenuItem();
        MenPedidos = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        MenComprobantes = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MenCalificacion = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MenSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBar.setMaximumSize(new java.awt.Dimension(379, 32768));
        menuBar.setMinimumSize(new java.awt.Dimension(379, 39));
        menuBar.setPreferredSize(new java.awt.Dimension(379, 39));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectrest/Presentacion/Imagenes/Maestro.png"))); // NOI18N
        jMenu1.setText("Maestros");

        MenMesas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenMesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectrest/Presentacion/Imagenes/Mesa.png"))); // NOI18N
        MenMesas.setText("Mesas");
        MenMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenMesasActionPerformed(evt);
            }
        });
        jMenu1.add(MenMesas);

        MenPlatos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenPlatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectrest/Presentacion/Imagenes/Plato.png"))); // NOI18N
        MenPlatos.setText("Platos");
        MenPlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenPlatosActionPerformed(evt);
            }
        });
        jMenu1.add(MenPlatos);

        MenClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectrest/Presentacion/Imagenes/Cliente.jpg"))); // NOI18N
        MenClientes.setText("Clientes");
        MenClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenClientesActionPerformed(evt);
            }
        });
        jMenu1.add(MenClientes);

        MenEmpleados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectrest/Presentacion/Imagenes/Empleados.png"))); // NOI18N
        MenEmpleados.setText("Empleados");
        MenEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenEmpleadosActionPerformed(evt);
            }
        });
        jMenu1.add(MenEmpleados);

        menuBar.add(jMenu1);

        MenPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectrest/Presentacion/Imagenes/Venta.png"))); // NOI18N
        MenPedidos.setText("Pedidos");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectrest/Presentacion/Imagenes/Pedido.png"))); // NOI18N
        jMenuItem1.setText("Módulo de Pedidos");
        MenPedidos.add(jMenuItem1);

        MenComprobantes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenComprobantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectrest/Presentacion/Imagenes/Comprobante.png"))); // NOI18N
        MenComprobantes.setText("Módulo de Comprobantes");
        MenPedidos.add(MenComprobantes);

        menuBar.add(MenPedidos);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectrest/Presentacion/Imagenes/Calificaciones.png"))); // NOI18N
        jMenu3.setText("Calificaciones");

        MenCalificacion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenCalificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectrest/Presentacion/Imagenes/Calificacion.png"))); // NOI18N
        MenCalificacion.setText("Módulo de Calificación");
        jMenu3.add(MenCalificacion);

        menuBar.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectrest/Presentacion/Imagenes/Cerrar.png"))); // NOI18N
        jMenu4.setText("Cerrar");

        MenSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectrest/Presentacion/Imagenes/Salir.png"))); // NOI18N
        MenSalir.setText("Salir del Sistema");
        MenSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenSalirActionPerformed(evt);
            }
        });
        jMenu4.add(MenSalir);

        menuBar.add(jMenu4);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Principal, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenEmpleadosActionPerformed
        Frm_Empleado frm = new Frm_Empleado();
        this.visibleFrame(frm);
    }//GEN-LAST:event_MenEmpleadosActionPerformed

    private void MenSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MenSalirActionPerformed

    private void MenMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenMesasActionPerformed
        Frm_Mesa frm = new Frm_Mesa();
        this.visibleFrame(frm);
    }//GEN-LAST:event_MenMesasActionPerformed

    private void MenClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenClientesActionPerformed
        Frm_Cliente frm = new Frm_Cliente();
        this.visibleFrame(frm);
    }//GEN-LAST:event_MenClientesActionPerformed

    private void MenPlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenPlatosActionPerformed
        Frm_Plato frm = new Frm_Plato();
        this.visibleFrame(frm);
    }//GEN-LAST:event_MenPlatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenCalificacion;
    private javax.swing.JMenuItem MenClientes;
    private javax.swing.JMenuItem MenComprobantes;
    private javax.swing.JMenuItem MenEmpleados;
    private javax.swing.JMenuItem MenMesas;
    private javax.swing.JMenu MenPedidos;
    private javax.swing.JMenuItem MenPlatos;
    private javax.swing.JMenuItem MenSalir;
    private javax.swing.JDesktopPane Principal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
